- name: Install common packages
  apt:
    update_cache: yes
    name:
      - cron
      - sudo
      - python3
      - python3-pip

- name: Check installed packages
  package_facts:
    manager: apt

- name: Install passlib
  pip:
    name: passlib
