- name: Install Nginx and setcap/getcap tools
  apt:
    name:
      - nginx
      - libcap2-bin

- name: Allow nginx to bind to privileged ports
  community.general.capabilities:
    path: /usr/sbin/nginx
    capability: cap_net_bind_service=+ep
    state: present

- name: Start Nginx
  systemd:
    name: nginx
    enabled: true
    state: started

- name: Create htpasswd
  htpasswd:
    path: /etc/nginx/htpasswd
    name: treason
    password: "{{nginx_passwd}}"
    owner: www-data
    group: www-data
    mode: 0640
  notify:
    - Reload Nginx

- name: Stat letsencrypt directory
  stat:
    path: /etc/letsencrypt/live/coup.thebrown.net
  register: letsencrypt_dir
  tags: nginx-conf

- name: Add nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
  notify:
    - Reload Nginx
  tags: nginx-conf
